import { useState, type ChangeEvent } from 'react'
import { Download, Eye, LayoutDashboard, PackagePlus, Plus, RotateCcw, Save, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/Button'
import { useContent } from '@/features/content/ContentProvider'
import type { Category, Product } from '@/types/catalog'

type Tab = 'website' | 'products' | 'categories'
const fieldClass = 'min-h-11 w-full rounded-control border bg-white px-3 text-sm focus:border-brand'
const labelClass = 'grid gap-1.5 text-sm font-medium'

function TextField({ label, value, onChange, type = 'text' }: { label: string; value: string | number; onChange: (value: string) => void; type?: string }) {
  return <label className={labelClass}>{label}<input className={fieldClass} type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>
}

function ProductEditor({ product, onSave, onDelete }: { product: Product; onSave: (product: Product) => void; onDelete: () => void }) {
  const [draft, setDraft] = useState(product)
  const update = <K extends keyof Product>(key: K, value: Product[K]) => setDraft((current) => ({ ...current, [key]: value }))
  return <details className="rounded-card border bg-white" open={product.id.startsWith('new-')}><summary className="cursor-pointer px-5 py-4 font-semibold">{product.name}</summary><div className="grid gap-4 border-t p-5 sm:grid-cols-2"><TextField label="Product name" value={draft.name} onChange={(value) => update('name', value)} /><TextField label="Slug" value={draft.slug} onChange={(value) => update('slug', value)} /><TextField label="Image URL" value={draft.image} onChange={(value) => update('image', value)} /><TextField label="Category slug" value={draft.category} onChange={(value) => update('category', value)} /><TextField label="Price (BDT)" type="number" value={draft.price} onChange={(value) => update('price', Number(value))} /><TextField label="Compare price" type="number" value={draft.compareAtPrice ?? ''} onChange={(value) => update('compareAtPrice', value ? Number(value) : undefined)} /><TextField label="Stock" type="number" value={draft.stock} onChange={(value) => update('stock', Number(value))} /><TextField label="Badge" value={draft.badge ?? ''} onChange={(value) => update('badge', value || undefined)} /><label className={`${labelClass} sm:col-span-2`}>Description<textarea className={`${fieldClass} min-h-24 py-3`} value={draft.description} onChange={(event) => update('description', event.target.value)} /></label><label className={labelClass}>Source<select className={fieldClass} value={draft.source} onChange={(event) => update('source', event.target.value as Product['source'])}><option value="local">Local</option><option value="global">Global</option></select></label><div className="flex flex-wrap items-end gap-5 text-sm">{(['featured', 'trending', 'isNew'] as const).map((key) => <label key={key} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={Boolean(draft[key])} onChange={(event) => update(key, event.target.checked)} />{key === 'isNew' ? 'New arrival' : key[0].toUpperCase() + key.slice(1)}</label>)}</div><div className="flex gap-2 sm:col-span-2"><Button onClick={() => onSave(draft)}><Save size={16} />Save product</Button><Button variant="secondary" className="text-danger" onClick={onDelete}><Trash2 size={16} />Delete</Button></div></div></details>
}

export default function ContentStudioPage() {
  const { content, updateContent, updateProduct, addProduct, removeProduct, updateCategory, addCategory, removeCategory, resetContent, exportContent } = useContent()
  const [tab, setTab] = useState<Tab>('website')
  const updateSite = (key: keyof typeof content.site, value: string) => updateContent({ ...content, site: { ...content.site, [key]: value } })
  const updateHero = (key: keyof typeof content.hero, value: string) => updateContent({ ...content, hero: { ...content.hero, [key]: value } })
  const newProduct = () => addProduct({ id: `new-${Date.now()}`, slug: 'new-product', name: 'New product', image: '', price: 0, rating: 5, reviewCount: 0, source: 'local', category: content.categories[0]?.slug ?? 'general', description: '', stock: 0 })
  const newCategory = () => addCategory({ id: `new-${Date.now()}`, name: 'New category', slug: 'new-category', image: '', itemCount: 0 })
  const download = () => { const blob = new Blob([exportContent()], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'hatbazar-content.json'; anchor.click(); URL.revokeObjectURL(url) }
  const importFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { updateContent(JSON.parse(String(reader.result)) as typeof content) } catch { window.alert('That file is not valid content JSON.') } }; reader.readAsText(file) }

  return <div className="min-h-screen bg-slate-100"><header className="sticky top-0 z-20 border-b bg-white"><div className="mx-auto flex max-w-container items-center justify-between gap-4 px-4 py-4 sm:px-6"><div><p className="text-xs font-bold uppercase tracking-wider text-brand">Administration</p><h1 className="text-xl font-bold">Content Studio</h1></div><div className="flex gap-2"><Link to="/" className="inline-flex min-h-11 items-center gap-2 rounded-control border px-4 text-sm font-semibold"><Eye size={16} />View store</Link><Button variant="secondary" onClick={download}><Download size={16} /><span className="hidden sm:inline">Export</span></Button><label className="inline-flex min-h-11 cursor-pointer items-center rounded-control border bg-white px-4 text-sm font-semibold">Import<input type="file" accept="application/json" className="sr-only" onChange={importFile} /></label></div></div></header><div className="mx-auto grid max-w-container gap-6 px-4 py-6 lg:grid-cols-[220px_1fr] lg:px-8"><aside className="h-fit rounded-card border bg-white p-2">{([['website', LayoutDashboard, 'Website'], ['products', PackagePlus, 'Products'], ['categories', LayoutDashboard, 'Categories']] as const).map(([value, Icon, label]) => <button key={value} onClick={() => setTab(value)} className={`flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm font-semibold ${tab === value ? 'bg-brand text-white' : 'hover:bg-slate-100'}`}><Icon size={18} />{label}</button>)}<button onClick={() => window.confirm('Restore all default content?') && resetContent()} className="mt-2 flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm font-semibold text-danger hover:bg-red-50"><RotateCcw size={18} />Restore defaults</button></aside><main>
    {tab === 'website' && <div className="space-y-6"><section className="rounded-card border bg-white p-5"><h2 className="type-h3">Store identity</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><TextField label="Store name" value={content.site.name} onChange={(value) => updateSite('name', value)} /><TextField label="Tagline" value={content.site.tagline} onChange={(value) => updateSite('tagline', value)} /><TextField label="Support phone" value={content.site.supportPhone} onChange={(value) => updateSite('supportPhone', value)} /><TextField label="Support email" value={content.site.supportEmail} onChange={(value) => updateSite('supportEmail', value)} /><TextField label="Currency symbol" value={content.site.currencySymbol} onChange={(value) => updateSite('currencySymbol', value)} /><TextField label="Announcement" value={content.announcement} onChange={(value) => updateContent({ ...content, announcement: value })} /></div></section><section className="rounded-card border bg-white p-5"><h2 className="type-h3">Homepage hero</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><TextField label="Eyebrow" value={content.hero.eyebrow} onChange={(value) => updateHero('eyebrow', value)} /><TextField label="Headline" value={content.hero.title} onChange={(value) => updateHero('title', value)} /><TextField label="Highlighted text" value={content.hero.highlight} onChange={(value) => updateHero('highlight', value)} /><TextField label="Image URL" value={content.hero.image} onChange={(value) => updateHero('image', value)} /><label className={`${labelClass} sm:col-span-2`}>Description<textarea className={`${fieldClass} min-h-24 py-3`} value={content.hero.description} onChange={(event) => updateHero('description', event.target.value)} /></label><TextField label="Primary button" value={content.hero.primaryCta} onChange={(value) => updateHero('primaryCta', value)} /><TextField label="Secondary button" value={content.hero.secondaryCta} onChange={(value) => updateHero('secondaryCta', value)} /></div></section></div>}
    {tab === 'products' && <div><div className="mb-5 flex items-center justify-between"><div><h2 className="type-h2">Products</h2><p className="text-sm text-muted">Changes appear in the store immediately.</p></div><Button onClick={newProduct}><Plus size={16} />Add product</Button></div><div className="space-y-3">{content.products.map((product) => <ProductEditor key={product.id} product={product} onSave={updateProduct} onDelete={() => removeProduct(product.id)} />)}</div></div>}
    {tab === 'categories' && <div><div className="mb-5 flex items-center justify-between"><div><h2 className="type-h2">Categories</h2><p className="text-sm text-muted">Edit marketplace navigation and category cards.</p></div><Button onClick={newCategory}><Plus size={16} />Add category</Button></div><div className="space-y-3">{content.categories.map((category) => <CategoryEditor key={category.id} category={category} onSave={updateCategory} onDelete={() => removeCategory(category.id)} />)}</div></div>}
  </main></div></div>
}

function CategoryEditor({ category, onSave, onDelete }: { category: Category; onSave: (category: Category) => void; onDelete: () => void }) {
  const [draft, setDraft] = useState(category)
  return <div className="grid gap-3 rounded-card border bg-white p-4 sm:grid-cols-[1fr_1fr_2fr_auto]"><TextField label="Name" value={draft.name} onChange={(name) => setDraft({ ...draft, name })} /><TextField label="Slug" value={draft.slug} onChange={(slug) => setDraft({ ...draft, slug })} /><TextField label="Image URL" value={draft.image} onChange={(image) => setDraft({ ...draft, image })} /><div className="flex items-end gap-2"><Button onClick={() => onSave(draft)} aria-label="Save category"><Save size={16} /></Button><Button variant="secondary" onClick={onDelete} aria-label="Delete category"><Trash2 size={16} /></Button></div></div>
}
